apiVersion: v2
name: snyk-universal-broker
version: 0.0.1
description: A Helm chart for Kubernetes
type: application
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x