apiVersion: v2
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.30.0
description: A Helm chart for Kubernetes
name: snyk-universal-broker
type: application
version: 0.0.1
