version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

jobs:
  validate_charts:
    docker:
      - image: alpine/k8s:1.28.14
    resource_class: small
    steps:
      - checkout
      - run:
          name: Helm dependencies
          command: helm dep up
          working_directory: 
            snyk-universal-broker
      - run:
          name: Run helm unittest
          command: helm unittest .
          working_directory: 
            snyk-universal-broker

  validate_documentation:
    docker:
      - image: cimg/node:20.18.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: Run the readme generator
          command: 
            npx @bitnami/readme-generator-for-helm -v snyk-universal-broker/values.yaml -r README.md
      - run:
          name: Check if files in CI have changed
          command: |
            if [[ -n $(git diff --name-only README.md) ]]; then
              echo "README content not synchronised with values.yaml"
              exit 1
            fi

  publish:
    docker:
      - image: cimg/node:22.9 
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm ci
      - run:
          name: Install Helm
          command: |
            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - run:
          name: Docker Login for OCI Push
          command: |
           echo "$DOCKER_PASSWORD" | helm registry login -u snykdocker --password-stdin registry-1.docker.io
      - run:
          name: Run semantic-release
          command: npx semantic-release

workflows:
  validate_and_publish:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: hybrid-alerts
          trusted-branch: main
      - validate_charts
      - validate_documentation
      - publish:
          context:
            - team-broker-docker-hub
          requires:
            - validate_charts
            - validate_documentation
          filters:
            branches:
              only:
                - main
