version: 2.1

jobs:
  validate_charts:
    docker:
      - image: alpine/k8s:1.28.14
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Helm dependencies
          command: helm dep up
          working_directory: 
            snyk-universal-broker

      - run:
          name: Run helm unittest
          command: helm unittest .
          working_directory: 
            snyk-universal-broker

  publish:
    docker:
      - image: cimg/node:22.9 
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm ci

      - run:
          name: Set up Git
          command: |
            git remote set-url origin git@github.com/snyk/snyk-universal-broker-helmchart.git
            
      - run:
          name: Install Helm
          command: |
            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - run:
          name: Docker Login for OCI Push
          command: |
           echo "$DOCKER_PASSWORD" | helm registry login -u snykdocker --password-stdin registry-1.docker.io

          
      - run:
          name: Run semantic-release
          command: npx semantic-release
          environment:
            DOCKER_USERNAME: $DOCKER_USERNAME
            DOCKER_PASSWORD: $DOCKER_PASSWORD
            
      - run:
          name: Update Chart Version
          command: |
            CHART_DIR="snyk-universal-broker"
            NEW_VERSION=$(git describe --tags --abbrev=0)
            echo "Updating Chart.yaml to version $NEW_VERSION"
            sed -i "s/^version: .*/version: $NEW_VERSION/" $CHART_DIR/Chart.yaml

      - run:
          name: Package Helm Chart
          command: |
            helm dep up snyk-universal-broker
            helm package snyk-universal-broker
  
      - run:
          name: Push Helm Chart to OCI Registry
          command: |
            helm push snyk-universal-broker-*.tgz oci://registry-1.docker.io/snyk
          environment:
            DOCKER_USERNAME: $DOCKER_USERNAME
            DOCKER_PASSWORD: $DOCKER_PASSWORD

workflows:
  validate_and_publish:
    jobs:
      - validate_charts  
      - publish:
          requires:
            - validate_charts
          filters:
            branches:
              only:
                - main
