version: 2.1

jobs:
  validate_charts:
    docker:
      - image: alpine/k8s:1.28.14
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Helm dependencies
          command: helm dep up
          working_directory: 
            snyk-universal-broker

      - run:
          name: Run helm unittest
          command: helm unittest .
          working_directory: 
            snyk-universal-broker

  publish:
    docker:
      - image: cimg/node:22.9 
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm ci

      - run:
          name: Install Helm
          command: |
            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - run:
          name: Docker Login for OCI Push
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - run:
          name: Package Helm Chart
          command: |
            helm dep up snyk-universal-broker
            helm package snyk-universal-broker
          
      - run:
          name: Run semantic-release
          command: npx semantic-release
          environment:
            GH_TOKEN: $GH_TOKEN
            DOCKER_USERNAME: $DOCKER_USERNAME
            DOCKER_PASSWORD: $DOCKER_PASSWORD

      - run:
          name: Push Helm Chart to OCI Registry
          command: |
            helm registry login oci://registry-1.docker.io
            helm push snyk-universal-broker-*.tgz oci://registry-1.docker.io/snyk
          environment:
            DOCKER_USERNAME: $DOCKER_USERNAME
            DOCKER_PASSWORD: $DOCKER_PASSWORD

workflows:
  validate_and_publish:
    jobs:
      - validate_charts  
      - publish:
          requires:
            - validate_charts
          filters:
            branches:
              only:
                - main
