version: 2.1

jobs:
  validate_charts:
    machine:
      image: ubuntu-2204:current  # Use a Docker image that has Helm support or install Helm manually
    resource_class: medium
    steps:
      - checkout

      - run:
          name: Install Helm
          command: |
            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
            helm version

      - run:
          name: Install helm-unittest plugin
          command: |
            helm plugin install https://github.com/helm-unittest/helm-unittest

      - run:
          name: Run helm unittest
          command: |
            helm unittest snyk-universal-broker

workflows:
  validate:
    jobs:
      - validate_charts