version: 2.1

jobs:
  validate_charts:
    docker:
      - image: alpine/k8s:1.28.14
    resource_class: medium
    steps:
      - checkout

      - run:
          name: Install helm-unittest plugin
          command: |
            helm plugin install https://github.com/helm-unittest/helm-unittest

      - run:
          name: Run helm unittest
          command: |
            helm unittest snyk-universal-broker

workflows:
  validate:
    jobs:
      - validate_charts