{{- if and .Values.caCert ( not .Values.caCertSecret.name ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.caCertSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
data:
  caCert: {{ .Values.caCert | b64enc | nindent 4 }}
{{- end }}
