{{- if and .Values.commitSigning.enabled ( not .Values.commitSigningSecret.name ) }}
{{- $unsetKeys:= list -}}
{{- range ( unset .Values.commitSigning "enabled" | keys ) -}}
{{- if not (get $.Values.commitSigning . ) }}
{{- $unsetKeys = append $unsetKeys . -}}
{{- end }}
{{- end }}
{{- if gt (len $unsetKeys) 0 -}}
{{- fail (printf "Missing value(s) under .Values.commitSigning for: %s" (join "," $unsetKeys) ) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.commitSigningSecretName" . }}
  namespace: {{ .Release.Namespace }}
labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
data:
  GPG_PRIVATE_KEY: {{ .Values.commitSigning.gpgPrivateKey | b64enc }}
  GPG_PASSPHRASE: {{ .Values.commitSigning.passphrase | b64enc }}
  GIT_COMMITER_NAME: {{ .Values.commitSigning.name | b64enc }}
  GIT_COMMITER_EMAIL: {{ .Values.commitSigning.email | b64enc }}
{{- end }}
