{{- if .Values.ingress.enabled }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  annotations:
    {{- if or .Values.ingress.annotations .Values.commonAnnotations }}
    {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.ingress.annotations .Values.commonAnnotations ) "context" . ) }}
    {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.ingress.ingressClassName (eq "true" (include "common.ingress.supportsIngressClassname" .)) }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hostname }}
    - host: {{ tpl .Values.ingress.hostname . }}
      http:
        paths:
          {{- if $.Values.ingress.extraPaths }}
          {{- include "common.tplvalues.render" (dict "value"  $.Values.ingress.extraPaths "context" $) | nindent 10 }}
          {{- end }}
          - path: {{ $.Values.ingress.path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
            pathType: {{ $.Values.ingress.pathType }}
            {{- end }}
            backend: 
              service:
                name: {{ include "common.names.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
    {{- range .Values.ingress.extraHosts }}
    - host: {{ .name }}
      http:
        paths:
          - path: {{ default "/" .path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: {{ default "prefix" .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ include "common.names.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    {{- if and .Values.ingress.tls.enabled }}
    {{- if $.Values.ingress.existingSecret }}
    - secretName: {{ .Values.ingress.existingSecret }}
    {{- else }}
    - secretName: {{ printf "%s-tls" (tpl .Values.ingress.hostname .) | trunc 63 | trimSuffix "-" }}
    {{- end }}
      hosts:
        - {{ .Values.ingress.hostname | quote }}
  {{- end }}
{{- end }}
{{- end }}