{{- if .Values.ingress.enabled }}
{{- if and .Values.ingress.tls.enabled .Values.ingress.secrets (not .Values.ingress.tls.existingSecret) }}
{{- range .Values.ingress.secrets }}
{{- if and .certificate .key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $.Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .certificate | b64enc }}
  tls.key: {{ .key | b64enc }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
