---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-broker-platform-auth" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
type: Opaque
stringData:
  deploymentId: {{ .Values.deploymentId | quote }}
  clientId: {{ .Values.clientId | quote }}
  clientSecret: {{ .Values.clientSecret | quote }}
---
{{- if and (not .Values.existingSecrets) (or .Values.brokerToken .Values.credentialReferences.GITHUB_TOKEN .Values.credentialReferences.GITLAB_TOKEN .Values.credentialReferences.BITBUCKET_PASSWORD .Values.credentialReferences.AZURE_REPOS_TOKEN) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-broker-scm-credential" (include "common.names.fullname" .) }}
type: Opaque
stringData:
  BROKER_TOKEN: {{ .Values.brokerToken | quote }}
  {{- if .Values.credentialReferences.GITHUB_TOKEN }}
  GITHUB_TOKEN: {{ .Values.credentialReferences.GITHUB_TOKEN | quote }}
  {{- end }}
  {{- if .Values.credentialReferences.GITLAB_TOKEN }}
  GITLAB_TOKEN: {{ .Values.credentialReferences.GITLAB_TOKEN | quote }}
  {{- end }}
  {{- if .Values.credentialReferences.BITBUCKET_PASSWORD }}
  BITBUCKET_PASSWORD: {{ .Values.credentialReferences.BITBUCKET_PASSWORD | quote }}
  {{- end }}
  {{- if .Values.credentialReferences.AZURE_REPOS_TOKEN }}
  AZURE_REPOS_TOKEN: {{ .Values.credentialReferences.AZURE_REPOS_TOKEN | quote }}
  {{- end }}
{{- end }}