{{- if not .Values.credentialReferencesSecret.name }}
{{- include "snyk-broker.credentialReferences" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.credentialReferencesSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.credentialReferences }}
  {{- if not (hasSuffix ".pem" $key) }}
  {{ $key }}: {{ $value | quote }}
  {{- else }}
  {{/* For .pem files, use the key as both env var name and filename */}}
  {{ $key }}: |-
    {{- $value | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
---
{{- if not .Values.platformAuthSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.snykPlatformSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
type: Opaque
stringData:
  DEPLOYMENT_ID: {{ .Values.deploymentId | quote }}
  CLIENT_ID: {{ .Values.clientId | quote }}
  CLIENT_SECRET: {{ .Values.clientSecret | quote }}
{{- end }}
