---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-broker-platform-auth" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
type: Opaque
stringData:
  deploymentId: {{ .Values.deploymentId | quote }}
  clientId: {{ .Values.clientId | quote }}
  clientSecret: {{ .Values.clientSecret | quote }}
---
{{- if not .Values.existingSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-universal-broker-scm-credential-reference" (include "common.names.fullname" .) }}
type: Opaque
stringData:
{{- range $key, $value := .Values.credentialReferences }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}