---
{{- if and (.Values.httpsCert) (.Values.httpsKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{- printf "%s-certs" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.httpsCert | b64enc | nindent 4 }}
  tls.key: {{ .Values.httpsKey | b64enc | nindent 4 }}
---
{{- end }}
{{- if .Values.caCert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{- printf "%s-cacerts" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
data:
  cacert: {{ .Values.caCertFile | trim |  b64enc | nindent 4}}
{{- end }}