---
{{- if and (.Values.httpsCert) (.Values.httpsKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{- printf "%s-certs" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ (.Files.Get .Values.httpsCert) | b64enc | quote }}
  tls.key: {{ (.Files.Get .Values.httpsKey) | b64enc | quote }}
---
{{- end }}
{{- if or .Values.caCert .Values.caCertFile }}
apiVersion: v1
kind: Secret
metadata:
  name: {{- printf "%s-cacerts" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
data:
{{- if and .Values.caCert (not .Values.caCertFile) }}
{{ (.Files.Glob .Values.caCert).AsSecrets | nindent 2 }}
{{- else if and .Values.caCertFile (not .Values.caCert) }}
  cacert: {{ .Values.caCertFile | trim |  b64enc | nindent 4}}
{{- end }}
{{- end }}