---
{{- if and (.Values.localWebServer.certificate) (.Values.localWebServer.key) (not .Values.localWebServerSecret.name ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.localWebServer.certificate | b64enc | nindent 4 }}
  tls.key: {{ .Values.localWebServer.key | b64enc | nindent 4 }}
---
{{- end }}
