---
{{- if and (.Values.localWebServer.certificate) (.Values.localWebServer.key) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.localWebServer.certificate | b64enc | nindent 4 }}
  tls.key: {{ .Values.localWebServer.key | b64enc | nindent 4 }}
---
{{- end }}
{{- if and .Values.caCert ( not .Values.caCertSecret.name ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.caCertSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
data:
  cacert: {{ .Values.caCert | b64enc | nindent 4 }}
{{- end }}
---
{{- if .Values.ingress.enabled }}
{{- if and .Values.ingress.tls.enabled .Values.ingress.secrets }}
{{- range .Values.ingress.secrets }}
{{- if and .certificate .key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $.Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .certificate | b64enc }}
  tls.key: {{ .key | b64enc }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
