---
{{- if and (.Values.localWebServer.certificate) (.Values.localWebServer.key) (not .Values.localWebServerSecret.name ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.localWebServer.certificate | b64enc | nindent 4 }}
  tls.key: {{ .Values.localWebServer.key | b64enc | nindent 4 }}
---
{{- end }}
{{- if .Values.ingress.enabled }}
{{- if and .Values.ingress.tls.enabled (not .Values.ingress.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-tls" (tpl .Values.ingress.hostname .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $.Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.secret.cert | b64enc | b64enc }}
  tls.key: {{ .Values.ingress.tls.secret.key | b64enc | b64enc }}
---
{{- end }}
{{- end }}
