name: Validate Charts

on:
  push:
    branches:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Run helm unittest
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest
          helm dep up hybrid-platform/charts/hybrid-platform-egress 
          helm unittest hybrid-platform